version: '3.1'
services:
  db:
    image: postgres:9.3.5
    expose:
      - "5432"

  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/myapp
      - RAILS_ENV=production
    ports:
      - "3000:3000"
    links:
      - db
    tty: true
    volumes:
      - .:/myapp
